version: '3'

services:
  qbot:
    image: ghcr.io/linyuan0213/qbot:latest
    container_name: qbot
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Shanghai
      - QB_CONF=/etc/qbot/config.yaml
    volumes:
      - /path/to/qbot:/etc/qbot
    restart: unless-stopped